package com.mstransaction.mstransaction.domain.enumTypes;

public enum Currency {
	AOA, AUD, GBP, EUR, KMF, USD, KYD, ILS, XOF, SSP, NZD, EGP, LRD,
	SBD, UZS, ZWL, XAF, AED, ZMW, KHR, VND, XPF, ZAR, GYD, MZN, TMT,
	LAK, HUF, ARS, TRY, HTG, SYP, SEK, BZD, CLP, RSD, DZD, BOB, CKD,
	VUV, NAD, YER, MOP, MUR, AWG, KGS, GTQ, TOP, GNF, TTD, JMD, BSD,
	RUB, LSL, MMK, BTN, MRU, CNY, PYG, DKK, NOK, GHS, MWK, PGK, SZL,
	JOD, CAD, MAD, MNT, ISK, THB, BGN, NIO, GIP, XCD, COP, BRL, NPR,
	KPW, ANG, SRD, KWD, SOS, CDF, ALL, HNL, SDG, HKD, LKR, BDT, MGA,
	BHD, MKD, UAH, ERN, AZN, SLL, DJF, UYU, GMD, MDL, AFN, BND, FJD,
	MXN, CHF, RWF, BMD, TWD, JPY, QAR, BWP, LBP, LYD, MYR, CRC, BAM,
	BIF, CVE, OMR, BYN, BBD, TZS, WST, ETB, INR, MVR, SCR, UGX, FKP,
	STN, IQD, PLN, TJS, KES, KZT, PAB, SGD, NGN, RON, CZK, AMD, VES,
	PHP, PEN, KRW, DOP, IRR, CUC, SAR, GEL, PKR, SHP, TND, IDR
}
