version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - "9091:8080"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db
      DB_SCHEMA: public
      DB_DATABASE: keycloak_db
      DB_USER: admin
      DB_PASSWORD: pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ['start-dev']
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:




