version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - "9091:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ['start-dev']

  user-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: user-db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:mysql
      - initdb:/docker-entrypoint-initdb.d
    expose:
      - "3307"
volumes:
  mysql-data:
  initdb:
    driver: local


