server:
  port: 8082
  context-path: /user/

spring:
  application:
    name: ms-user
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.triwal.tech/realms/triwal-realm-dev
          jwk-set-uri: https://keycloak.triwal.tech/realms/triwal-realm-dev/protocol/openid-connect/certs

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# ESTO ME PERMITE ENVIAR EL LINK AL CORREO PARA HABILITAR NUEVAMENTE LA CUENTA
  mail:
    host: smtp.gmail.com
    port: 587
    username: triwalwebapp@gmail.com
    password: etgd braa odfz aqgv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://eureka.triwal.tech/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

jwtConverter:
  auth:
    converter:
      resource-id: triwal-app
      main-attr: preferred_username
