server:
  port: 8082
  context-path: /user/

spring:
  application:
    name: ms-user
  config:
    import: optional:configserver:http://localhost:8888

# ESTO ME PERMITE ENVIAR EL LINK AL CORREO PARA HABILITAR NUEVAMENTE LA CUENTA
  mail:
    host: smtp.gmail.com
    port: 587
    username: triwalwebapp@gmail.com
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

